# Generated by Django 5.1.2 on 2024-10-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0002_rename_stat_time_extracurricularactivity_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracurricularactivity',
            name='activity',
            field=models.CharField(choices=[('running', 'Бег'), ('swimming', 'Плавание'), ('bicycle', 'Велосипед'), ('basketball', 'Баскетбол'), ('volleyball', 'Волейбол'), ('knitting', 'Вязание'), ('painting', 'Рисование'), ('computer', 'Компьютер'), ('friends', 'Друзья'), ('TV', 'Телевизор')], max_length=100),
        ),
        migrations.AlterField(
            model_name='extracurricularactivity',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=10),
        ),
    ]
